## Function

In [1]:
def my_function():
    "This prints a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [7]:
def printme(nama): #parameter #nama holds value Titis/ Nama saya adalah ....
    "This prints a nama string into this function"
    print(nama)

In [8]:
printme("Titis") #argument

Titis


In [9]:
printme("Nama saya adalah ....")

Nama saya adalah ....


## Required Argument

In [19]:
def printme(nama, alamat):
    "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

In [20]:
printme("Titis", "Purwokerto")

Titis
Purwokerto


## Keyword Arguments

In [21]:
printme(alamat="Purwokerto", nama="Titis")

Titis
Purwokerto


In [22]:
def printme(nama = "Titis", alamat = "Purwokerto"):
    "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

In [23]:
printme()

Titis
Purwokerto


In [24]:
printme("Inalum")

Inalum
Purwokerto


In [29]:
printme(alamat="Batu Bara")

Titis
Batu Bara


In [30]:
printme("Inalum", "Batu Bara")

Inalum
Batu Bara


## Variable-length arguments

In [39]:
def printinfo(arg1, *vartuple):
    "This prints a variable passed arguments"
    print("Output is: ")
    print (arg1)
    for var in vartuple:
        print(var)
    return;

In [40]:
printinfo(30)

Output is: 
30


In [41]:
printinfo(1, 2, 3, 4, 5, 6, 7, 8, 9)

Output is: 
1
2
3
4
5
6
7
8
9


## Anonymous Function - Lambda

In [42]:
sum = lambda arg1, arg2: arg1 + arg2;

In [43]:
sum(10, 30)

40

In [44]:
print("Value of total:", sum(10, 30))

Value of total: 40


## Return Statement

In [60]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [61]:
sum(10, 40)

(50, 100)

## Scope of Variables

In [80]:
meow = 30 #variable global/ outside

def jumlahHewan():
    bunny = 20 #variable lokal/ inside
    hewan = meow + bunny
    return hewan

def tambahHewan():
    puppies = 15 #variable lokal
    tambahan = puppies + meow
    return tambahan

In [81]:
jumlahHewan()

50

In [82]:
tambahHewan()

45

In [83]:
import sys ## memanipulasi system yang ada di komputer

## menampilkan modul/ package yang tersimpan di komputer

In [84]:
sys.path

['C:\\Users\\TITIS PRADHITYA',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\python37.zip',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\DLLs',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3',
 '',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\TITIS PRADHITYA\\.ipython']

In [86]:
sys.path.append(r'/Users/TITIS PRADHITYA/Desktop/H8package')

In [87]:
sys.path

['C:\\Users\\TITIS PRADHITYA',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\python37.zip',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\DLLs',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3',
 '',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\TITIS PRADHITYA\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\TITIS PRADHITYA\\.ipython',
 '/Users/TITIS PRADHITYA/Desktop/H8package']

In [ ]:
import mod

In [93]:
mod.s

'Hactiv8 Inalumfor data Science'

In [94]:
mod.a

[100, 200, 300]

In [95]:
mod.foo('Titis')

Titis


In [96]:
from mod import s, foo

In [97]:
s

'Hactiv8 Inalumfor data Science'

In [98]:
foo('Titis')

Titis


In [99]:
from mod import *

In [100]:
s

'Hactiv8 Inalumfor data Science'

In [101]:
from mod import s as string

In [102]:
string

'Hactiv8 Inalumfor data Science'

In [103]:
import mod as my_module

In [104]:
my_module.a

[100, 200, 300]

In [105]:
my_module.s

'Hactiv8 Inalumfor data Science'

In [106]:
import numpy as np

In [112]:
sys.path.append(r'/Users/TITIS PRADHITYA/Desktop/')

In [113]:
import H8package.mod

In [114]:
import H8package.mod

H8package.mod.s

'Hactiv8 Inalum for data Science'

In [116]:
from H8package.mod import s

In [117]:
s

'Hactiv8 Inalum for data Science'

In [118]:
!pip --version

pip 20.0.2 from C:\Users\TITIS PRADHITYA\anaconda3\lib\site-packages\pip (python 3.7)



In [119]:
!pip install requests

In [120]:
import requests

In [121]:
mod.s

'Hactiv8 Inalumfor data Science'

# Numpy (Numerical Python)

In [122]:
import numpy as np

In [124]:
## Creating Array

a = np.array([1, 2, 3])

In [125]:
a

array([1, 2, 3])

In [126]:
b = [1, 2, 3]

In [127]:
b

[1, 2, 3]

In [129]:
c = np.zeros(5)

In [134]:
print (c)

[0. 0. 0. 0. 0.]


In [135]:
d = np.ones(5)

In [136]:
print (d)

[1. 1. 1. 1. 1.]


In [139]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [140]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.arange(0, 20, 2) #start, stop, step (Array dari Nol sampai 20 dengan element 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [144]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
print(arr)

[1 2 3 4 5 6 7 8]


In [148]:
np.append(arr, [1, 2]) #Add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [151]:
arrnew = np.append(arr, [1, 2]) 

In [152]:
arrnew

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [153]:
np.sort(arrnew)

array([1, 1, 2, 2, 3, 4, 5, 6, 7, 8])

In [154]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [155]:
np.sort(arr) #sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Shape and Size

In [169]:
array_example = np.array([[[[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]]]])

In [170]:
print(array_example)

[[[[0 1 2 3]
   [4 5 6 7]]

  [[0 1 2 3]
   [4 5 6 7]]

  [[0 1 2 3]
   [4 5 6 7]]

  [[0 1 2 3]
   [4 5 6 7]]]]


In [171]:
array_example.ndim

4

In [172]:
array_example.size

32

In [173]:
array_example.shape #dimensi jika lebih dari 2 dimensi '3'

(1, 4, 2, 4)

#### Reshape

In [181]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [182]:
b = a.reshape(3, 2)

In [183]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [188]:
c = a.reshape(6, 1)

In [189]:
print(c)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


#### Convert 1D to 2D

In [190]:
a

array([0, 1, 2, 3, 4, 5])

In [191]:
a.shape

(6,)

In [192]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [194]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [195]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [196]:
print(a.shape)

(6,)


In [199]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [200]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


#### indexing and slicing

In [201]:
data = np.array([1, 2, 3])

In [202]:
data[0]

1

In [203]:
data[1]

2

In [205]:
data[0:2]

array([1, 2])

In [206]:
data[1:]

array([2, 3])

In [207]:
data[-2]

2

In [208]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [209]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [212]:
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [213]:
a[a>8]

array([ 9, 10, 11, 12])

In [214]:
lebih_lima = (a >= 5)

a[lebih_lima]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [215]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#### Create array from exiting data

In [216]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [221]:
arr1 = arr[3:9]

print(arr1)

[4 5 6 7 8 9]


In [222]:
a_1 = np.array([[1, 1],
               [2, 2]])

print(a_1)

[[1 1]
 [2 2]]


In [223]:
a_2 = np.array([[3, 3],
               [4, 4]])

print(a_2)

[[3 3]
 [4 4]]


In [224]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [225]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [226]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [228]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

#### view and copy

In [229]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [231]:
b = a.view()

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [232]:
c = a.copy()

print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [233]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [234]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Basic array operations

In [235]:
a_1

array([[1, 1],
       [2, 2]])

In [236]:
a_2

array([[3, 3],
       [4, 4]])

In [237]:
a_2 - a_1

array([[2, 2],
       [2, 2]])

In [238]:
a_2 + a_1

array([[4, 4],
       [6, 6]])

In [239]:
a_2 * a_1

array([[3, 3],
       [8, 8]])

In [240]:
a_2 / a_1

array([[3., 3.],
       [2., 2.]])

In [241]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [242]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [244]:
arr.sum() #untuk menjumlahkan seluruh array

55

In [245]:
a_1

array([[1, 1],
       [2, 2]])

In [246]:
a_1.sum()

6

In [247]:
a_1.sum(axis=0)

array([3, 3])

In [248]:
a_1.sum(axis=1)

array([2, 4])

In [250]:
print(a_1)

[[1 1]
 [2 2]]


In [249]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [251]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [252]:
a.sum()

78

In [254]:
a.min()

1

In [255]:
a.max()

12

In [256]:
a.min(axis=0)

array([1, 2, 3, 4])

In [257]:
a.min(axis=1)

array([1, 5, 9])

In [259]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [260]:
a.max(axis=1)

array([ 4,  8, 12])

In [261]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [262]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [264]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [265]:
np.random.random((3,2))

array([[0.37949061, 0.73857807],
       [0.77278506, 0.8132821 ],
       [0.5887527 , 0.17586009]])

### Matrix Arithmetic

In [267]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [269]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [270]:
print (data + ones)

[[2. 3.]
 [4. 5.]]


In [271]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [272]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [273]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [274]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [275]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

#### Matrix Indexing

In [276]:
data = np.array([[1,2], [3,4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [278]:
data[0,1]

2

In [281]:
data[2,1]

6

In [283]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [284]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [285]:
data[0:2, 1]

array([2, 4])

In [286]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [287]:
data.min()

1

In [288]:
data.min()

1

In [289]:
data.sum()

21

In [290]:
data.max(axis=1)

array([2, 4, 6])

In [291]:
data.max(axis=0)

array([5, 6])

#### Transposing and reshaping

In [292]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [293]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [295]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [297]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [299]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [300]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


#### ND Array (N-Dimensional Array)

In [305]:
ndarr = np.array([[[1,2], [3,4]],
                [[5,6], [7,8]]])

In [306]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [307]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [308]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [309]:
np.random.random((4,3,2))

array([[[0.90887901, 0.44137582],
        [0.38728256, 0.7324971 ],
        [0.90954274, 0.72387547]],

       [[0.29593188, 0.23513878],
        [0.32442013, 0.84369694],
        [0.66487428, 0.16703964]],

       [[0.95898468, 0.23172956],
        [0.60999345, 0.2283504 ],
        [0.2269806 , 0.8213859 ]],

       [[0.35317338, 0.45385146],
        [0.37619165, 0.42519893],
        [0.39863749, 0.1857488 ]]])

#### Flatten

In [312]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [313]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [322]:
a = np.random.rand(5)

In [323]:
print(a)

[0.20385858 0.5619234  0.63368481 0.59703319 0.50316412]


In [324]:
a.shape #rank 1 Array

(5,)

In [325]:
a.T

array([0.20385858, 0.5619234 , 0.63368481, 0.59703319, 0.50316412])

In [326]:
np.dot(a, a.T)

1.3684954317484495

In [337]:
a = np.random.rand(5, 1) #column vector
print(a)

[[0.43995123]
 [0.61735871]
 [0.1365644 ]
 [0.62522362]
 [0.17439387]]


In [338]:
a.shape

(5, 1)

In [339]:
a.T

array([[0.43995123, 0.61735871, 0.1365644 , 0.62522362, 0.17439387]])

In [340]:
np.dot(a, a.T)

array([[0.19355708, 0.27160772, 0.06008167, 0.2750679 , 0.0767248 ],
       [0.27160772, 0.38113178, 0.08430922, 0.38598725, 0.10766357],
       [0.06008167, 0.08430922, 0.01864983, 0.08538329, 0.02381599],
       [0.2750679 , 0.38598725, 0.08538329, 0.39090457, 0.10903516],
       [0.0767248 , 0.10766357, 0.02381599, 0.10903516, 0.03041322]])

In [341]:
a = np.random.rand(1, 5)

In [332]:
a.shape

(1, 5)